theme: jekyll-theme-dinky
title: Dishonored 1.1
description: This is a small WJ modlist for Dishonored bringing some of the quality of life features from Dishonored 2.
show_downloads: true
wabbajack:
  wabbajack_url: https://www.wabbajack.org/#/
